### ISSUE TITLE
remove hardcoded paths in existdb.py

### ISSUE THREAD

**Issue by balmas** [PerseusDL/Capitains-Toolkit#1]
remove the hardcoded paths from this code:

` def start(self):
        return [shell.Helper("/home/thibault/dev/CTS-API/build/build_dir//db/conf/bin/startup.sh")]

    def stop(self):
        print (self.user)
        if self.user.password:
            return [shell.Command("/home/thibault/dev/CTS-API/build/build_dir//db/conf/bin/shutdown.sh -p {0}".format(self.user.password))]
        else:
            return [shell.Command("/home/thibault/dev/CTS-API/build/build_dir//db/conf/bin/shutdown.sh")]
`

**Comment by PonteIneptique** [comment]
Closed since a LOOOONG time
